### ISSUE TITLE
Community agreements

### ISSUE THREAD

**Issue by danasalama** [hyphacoop/countermapland#55]
In the "add to *countermap" sidebar, Community agreements are mentioned twice - once at the top and once at the bottom. Is this necessary?

**Comment by writerly03** [comment]
https://docs.google.com/document/d/11kGyb8OCBjM0FcCyYFyHjq4OBw1rHC64WscD2RdIGFE/edit#heading=h.niewzckf87rb

**Comment by writerly03** [comment]
Add ToS to website - add to menu?

**Comment by inglenet** [comment]
updated the menu and created a community agreements wireframe. 
personally, I'm in favour of keeping a link to community agreements at the top and bottom of the submission page so that users can read the agreements in both contexts – guidelines for submissions, and what happens with their data – without scrolling up or down again.

**Comment by tripledoublev** [comment]
I removed the second appearance of the 'Community Agreements' link.
That was before I read @inglenet's comment.
Happy to add it again following today's test results

**Comment by writerly03** [comment]
Sarah added the CAs to the top and bottom of the form in the latest design
