### ISSUE TITLE
Data schema and structure

### ISSUE THREAD

**Issue by writerly03** [hyphacoop/countermapland#6]
Preliminary recommendations for data schema and structure

**Comment by writerly03** [comment]
@tripledoublev please add your notes about the state of the data sets here.

@inglenet if you have any thoughts on this piece, let us know!

**Comment by tripledoublev** [comment]
I'll use Monument Lab's National Monument Audit's system of processing data as a starting point. 
I'll then present the Canadian National Inventory of Military Memorials data format as an example of a data set used as initial data source for populating the map.
Finally, I'll add a preliminary process that could be used to add new data sources by using native-land.ca as an example.

## Monument Lab's approach
Looking at the [National Monument Audit repository](https://github.com/MonumentLab/national-monument-audit/), I extracted relevant information on how we could mimic such a system to parse, format and output data to be shown on the countermapland's web app.

Monument Lab did some incredible work on fetching data from multiple sources and processing it to populate their own dataset. It allows to work with multiple data structure and process it in such a way that these varied sources become uniform.
This is set up with a main config file ([data-model.json](https://github.com/MonumentLab/national-monument-audit/blob/main/config/data-model.json)) that contains all the logic for generating the data set. Then the different sources are set from a directory that contains one JSON file per data source that is processed. Each of these files contains the logic for how the source data set should be parsed and mapped to the study set fields.
They use a series of [./scripts/](https://github.com/MonumentLab/national-monument-audit/tree/main/scripts) that runs python code that is used to preprocess data sources. This includes scripts for downloading and parsing websites. This ensures that it can fetch the latest data when the site is built (when dealing with databases that have on-going updates).

Running these scripts fetches the data, processes it and builds everything required by the app's front-end. It defines data sources input schema and ouput structure.

## [National Inventory of Canadian Military Memorials](https://open.canada.ca/data/dataset/f62a5118-5f75-4166-9fd9-fff99b3f177c)
Similar to Monument's Lab National Monument Audit, we will be dealing with data coming from different sources. Even when data comes from a multitude of sources with different structures, we should start by looking at the specificity of a single source's schema to see what we want to show.

 The raw dataset for Canadian Military Memorials, here are

**Comment by tripledoublev** [comment]
# Mapping the fields from the Monument Catalogue sheet to find their equivalent in the National Inventory of Canadian Military Memorials

I used the Monument Catalogue Canada spreadsheet and compared its fields to the Canadian Military Memorials.

There are 4 categories: 'Exact or easy matches', 'Potential matches', 'Unique to Monument Catalogue' and 'Unique to Military Memorials'.

The goal of this is to see what these have in commons and get a better understanding of their data structure.

***  
## Exact/Easy Matches

| MONUMENT CATALOGUE "CANADA" Field       | National Inventory of Canadian Military Memorials Field |
|-----------------------------------------|--------------------------------------------------------|
| COORDINATES - LAT / X                   | latitude                                               |
| COORDINATES - LONG/ Y                   | longitude                                              |
| STREET ADDRESS                          | address_e / address_f                                  |
| IMAGE 1- MAIN, IMAGE 2 - SECONDARY      | photo1, photo2, etc.                                   |
| PLAQUE/ MARKER TEXT / INSCRIPTION       | inscription1, inscription2, etc.                       |
| NAME / NAME (S)                         | name_e / name_f                                        |
| CITY (COLONIAL) - EXCLUDE FROM MAP      | municipality                                           |
| PROVINCE/ TERRITORY (COLONIAL)          | province_e / province_f                                |
| DESCRIPTION (LONG)                      | background_e / background_f                            |


*** 
## Potential Matches

Since some fields might not directly correspond but have related concepts or data, they are considered potential matches.

| MONUMENT CATALOGUE "CANADA" Field              | Potential National Inventory of Canadian Military Memorials Field Match | Reasoning                                      |
|------------------------------------------------|----------------------------------------------------------------------------|------------------------------------------------|
| ARTIST/ CREATOR                                | photo_credit, created_by                                                   | Creator of the memorial or image source        |
| AGENCIES SPONSORING/ MANAGING THE SITE         | caretaker_e / caretaker_f                                                  | Entity responsible for the memorial's upkeep   |
| OBJECT TYPE                                    | type_e / type_f                                                            | Classification of the memorial or subject      |
| DATA SOURCE/S, DATA SOURCE/S URL               | organization, photo_credit                                                 | Information or image sourcing                  |


***  
## Unmatched Fields in MONUMENT CATALOGUE "CANADA"
| MONUMENT CATALOGUE "CANADA" Field                                                             |
|------------------------------------------------------------------------------------------------|
| DISCLAIMER                                                                                     |
| ON THE TRADITIONAL LANDS OF (DATA FROM NATIVE-LAND.CA - CONTACT LOCAL NATIONS TO VERIFY)       |
| YEAR DEDICATED                                                                                 |
| YEAR CONSTRUCTED                                                                               |
| USE TYPES, USE TYPES 2                                                                         |
| SUBJECTS, SUBJECTS 2, SUBJECTS 3, SUBJECTS 4                                                   |
| HONOREES, HONOREES 2 through HONOREES 33                                                       |
| TAGS, TAGS 2                                                                                   |
| COMMUNITIES IMPACTED (CROWD-SOURCED)                                                           |
| ISSUES REPRESENTED (CROWD-SOURCED)                                                             |
| MATERIAL 1, MATERIAL 2, MATERIAL 3                                                             |
| AREA (SQ.KM), HEIGHT (M), WIDTH (M), DEPTH (M)                                                 |
| STAGING 1, STAGING 2, STAGING 3, STAGING COMMENTS                                              |
| GESTURE 1, GESTURE 2                                                                           |
| INCLUDES REPLICA?                                                                              |
| YEAR REMOVED (IF APPLICABLE)                                                                   |
| ADDITIONAL INFORMATION                                                                         |

***  
## Unmatched Fields in Canadian Military Memorials
| National Inventory of Canadian Military Memorials Field |
|---------------------------------------------------------|
| id                                                      |
| memorial_no                                             |
| province_e / province_f                                 |
| location_e / location_f                                 |
| ref_point_e / ref_point_f                               |
| is_it_cared_for_e / is_it_cared_for_f                   |
| condition_e / condition_f                               |
| surveyor                                                |
| organization                                            |
| abrev                                                   |
| publish                                                 |
| created_by                                              |
| created_on                                              |
| updated_by                                              |
| updated_on                                              |
| cared_for                                               |
| photo_credit_email                                      |
| photo5, photo6, etc.                                    |
| photo_credit_1 through photo_credit_6                   |
| street_view                                             |


This comprehensive listing ensures that each field, whether it has an exact/easy match, a potential match, or remains unmatched, is accounted for in our comparison of the Monument Catalogue "Canada" and the National Inventory of Canadian Military Memorials.

**Comment by writerly03** [comment]
- Some note about the above. Province is matched in both sets (is indicated as matched and unmatched)
- Honourees are included in the description in the MM data set; i.e. "<p>Erected in the early 1930s, this memorial is dedicated to the local war dead of the First World War. It is cared for by members of Royal Canadian Legion Branch No. 26 (Col. Moore).</p>"
- photo credit is not synonymous with artist but is with created by; however, this column is (almost entirely?) blank
- this data set includes a lot of detail about the person taking the photo and adding the entry; assume we don't want to collect any of this, but interesting to see here
- I like the location and reference points fields; these are relational and help ground the monument in place

**Comment by tripledoublev** [comment]
Removed province from unmatched. Will go over the rest to make sure all is accurate
